//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartsInventory {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class PathSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static PathSettings defaultInstance = ((PathSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PathSettings())));
        
        public static PathSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Daxxn\\Documents\\Electrical\\PartInvoices")]
        public string PartInvoiceDir {
            get {
                return ((string)(this["PartInvoiceDir"]));
            }
            set {
                this["PartInvoiceDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DigiKey")]
        public string DigiKeyDir {
            get {
                return ((string)(this["DigiKeyDir"]));
            }
            set {
                this["DigiKeyDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mouser")]
        public string MouserDir {
            get {
                return ((string)(this["MouserDir"]));
            }
            set {
                this["MouserDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Daxxn\\Documents\\PartsInventory\\settings.json")]
        public string SettingsPath {
            get {
                return ((string)(this["SettingsPath"]));
            }
            set {
                this["SettingsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Daxxn\\Documents\\Electrical\\Datasheets")]
        public string DatasheetsPath {
            get {
                return ((string)(this["DatasheetsPath"]));
            }
            set {
                this["DatasheetsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Daxxn\\Documents\\PartsInventory")]
        public string AppDataPath {
            get {
                return ((string)(this["AppDataPath"]));
            }
            set {
                this["AppDataPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data.json")]
        public string AppDataFileName {
            get {
                return ((string)(this["AppDataFileName"]));
            }
            set {
                this["AppDataFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BinLocations.json")]
        public string BinLocFileName {
            get {
                return ((string)(this["BinLocFileName"]));
            }
            set {
                this["BinLocFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Daxxn\\Documents\\Electrical\\KiCAD\\Designs")]
        public string KiCADProjects {
            get {
                return ((string)(this["KiCADProjects"]));
            }
            set {
                this["KiCADProjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Daxxn\\Documents\\Electrical\\Project BOMs")]
        public string BOMs {
            get {
                return ((string)(this["BOMs"]));
            }
            set {
                this["BOMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Daxxn\\Code\\C#\\Projects\\ElectricalCalculators\\ElectricalCalculators\\bin\\D" +
            "ebug\\net6.0-windows\\ElectricalCalculators.exe")]
        public string ElectricalCalcExe {
            get {
                return ((string)(this["ElectricalCalcExe"]));
            }
            set {
                this["ElectricalCalcExe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Daxxn\\SaturnPCB\\PCB Toolkit V8.10.exe")]
        public string SaturnPCBExe {
            get {
                return ((string)(this["SaturnPCBExe"]));
            }
            set {
                this["SaturnPCBExe"] = value;
            }
        }
    }
}
